name: bunny_dart
description: A Dart wrapper for Bunny.net APIs supporting various endpoints, including TUS Resumable Upload for efficient video uploads, ensuring seamless integration and enhanced performance.
version: 1.1.1
repository: https://github.com/devsdocs/bunny_dart

environment:
  sdk: ^3.7.2


dependencies:
  cross_file: ^0.3.4+2
  crypto: ^3.0.6
  dio: ^5.8.0+1
  path: ^1.9.1
  speed_test_dart: ^1.0.5+0
  web: ^1.1.1

dev_dependencies:
  args: ^2.7.0
  lint: ^2.8.0
  test: ^1.24.0
