name: bunny_dart
description: Dart wrapper for Bunny.net APIs
version: 1.0.1
repository: https://github.com/devsdocs/bunny_dart

environment:
  sdk: ^3.7.2


dependencies:
  cross_file: ^0.3.4+2
  crypto: ^3.0.6
  dio: ^5.8.0+1
  speed_test_dart: ^1.0.5+0

dev_dependencies:
  lint: ^2.8.0
  test: ^1.24.0
